# This is a basic workflow to help you get started with Actions

name: SQPackager ExampleApp build Qt6

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ testworkflow ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      -
        name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules : true
      -
       # I wish I could use Chocolatey or something else but it's a pain in the but
        name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
      -
        name: build
        id: build
        run: | 
              cd SQPackager
              qmake SQPackager.pro -spec win32-msvc "CONFIG+=release"
              nmake
              cd ..
              ls $env:HOME
              ls $env:HOME/../
              SQPackager/release/SQPackager.exe --build windows ExampleApp/sqproject.json
      -
         name: print output
         run: |
               echo "Standalone zip : ${{steps.build.outputs.sqpackager_win32_x64_standalone_zip}}"
               echo "Standalone 7zip : ${{steps.build.outputs.sqpackager_win32_x64_standalone_7zip}}"
               echo "Innosetup Installer : ${{steps.build.outputs.sqpackager_win32_x64_innosetup}}"